# Generated by Django 5.2.1 on 2025-05-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bird_counter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="bird",
            name="location",
            field=models.ForeignKey(
                help_text="The location of the observation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="birds",
                to="bird_counter.location",
            ),
        ),
    ]
